// src/components/language-switcher/language-switcher.tsx
import './language-switcher.css'

import { Component, createEffect, For } from 'solid-js'

import { Locale, locale, setLocale } from '@/i18n'

export const LanguageSwitcher: Component = () => {
  const languageList: { text: string; lan: Locale }[] = [
    {
      text: 'en_US',
      lan: 'en',
    },
    {
      text: 'zh_CN',
      lan: 'zh-cn',
    },
  ]

  createEffect(() => {
    if (locale() === 'en') {
      document.title = "I'm Yanren"
    } else {
      document.title = '我是炎忍'
    }
  })

  return (
    <div id="language-switcher">
      <ul class="language-list">
        <For each={languageList}>
          {(item) => {
            return (
              <li>
                <p
                  classList={{ active: locale() === item.lan }}
                  onClick={() => setLocale(item.lan)}
                  class="font-mono clickable"
                >
                  {locale() === item.lan ? `[ ${item.text} ]` : item.text}
                </p>
              </li>
            )
          }}
        </For>
      </ul>
    </div>
  )
}

// website/imyan.ren/src/lib/components/language-switcher/language-switcher.svelte
<script lang="ts">
  import { i18n, type Locale } from '$lib/i18n'

  const languageList: { text: string; lan: Locale }[] = [
    { text: 'en_US', lan: 'en' },
    { text: 'zh_CN', lan: 'zh-cn' },
  ]

  $effect(() => {
    if (i18n.locale === 'en') {
      document.title = "I'm Yanren"
    } else {
      document.title = '我是炎忍'
    }
  })

  const switchLang = (l: Locale) => {
    i18n.setLocale(l)
  }
</script>

<div id="language-switcher">
  <ul class="language-list">
    {#each languageList as item}
      <li>
        <button
          type="button"
          class="font-mono clickable"
          class:active={i18n.locale === item.lan}
          onclick={() => switchLang(item.lan)}
        >
          {i18n.locale === item.lan ? `[ ${item.text} ]` : item.text}
        </button>
      </li>
    {/each}
  </ul>
</div>

<style>
  #language-switcher {
    & .language-list {
      display: flex;
      align-items: flex-end;
    }
  }

  .language-list {
    & > li {
      margin-right: 20px;

      &:last-child {
        margin-right: 0;
      }

      & > button {
        cursor: pointer;
        background: transparent;
        border: none;
        padding: 0;
        margin: 0;
        color: var(--c-text);
        font-size: 1rem;
        transition: 0.2s;
        line-height: 1;
        opacity: 0.6;

        &:hover {
          opacity: 1;
          color: var(--c-text-hover);
          text-shadow: 0 0 5px var(--c-text-hover);
        }

        &.active {
          opacity: 1;
          color: var(--c-text-hover);
          font-weight: bold;
          text-shadow: 0 0 5px var(--c-text-hover);
        }
      }
    }
  }
</style>
