// src/lib/components/terminal/Terminal.svelte
<script lang="ts">
  import './terminal.css'
  interface Props {
    children?: import('svelte').Snippet
    class?: string
    [key: string]: any
  }
  let { children, class: className, ...others }: Props = $props()
</script>

<div class="terminal-box {className || ''}" {...others}>
  <div class="terminal-header">
    <div class="tui-controls">
      <!-- svelte-ignore a11y_click_events_have_key_events -->
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <span class="control clickable">[-]</span>
      <span class="control clickable">[□]</span>
      <span class="control clickable close">[×]</span>
    </div>
    <div class="tui-title">yanren@term:~</div>
  </div>
  <div class="terminal-content">
    {@render children?.()}
  </div>
</div>

// src/components/terminal/terminal.tsx
import './terminal.css'

import { Component, JSX, splitProps } from 'solid-js'

interface TerminalProps extends JSX.HTMLAttributes<HTMLDivElement> {
    children?: JSX.Element
}

export const Terminal: Component<TerminalProps> = (props) => {
    const [local, others] = splitProps(props, ['children', 'class', 'classList'])

    return (
        <div
            class={`terminal-box ${local.class || ''}`}
            classList={local.classList}
            {...others}
        >
            <div class="terminal-header">
                <div class="tui-controls">
                    <span class="control clickable">[-]</span>
                    <span class="control clickable">[□]</span>
                    <span class="control clickable close">[×]</span>
                </div>
                <div class="tui-title">yanren@term:~</div>
            </div>
            <div class="terminal-content">{local.children}</div>
        </div>
    )
}

export const TerminalLine: Component<{ children: JSX.Element; class?: string }> = (
    props
) => {
    return <div class={`line ${props.class || ''}`}>{props.children}</div>
}

export const TerminalHighlight: Component<{ children: JSX.Element }> = (
    props
) => {
    return <span class="highlight">{props.children}</span>
}

export const TerminalPrompt: Component<{ children?: JSX.Element }> = (
    props
) => {
    return (
        <TerminalLine>
            <TerminalHighlight>root@imyan.ren:~$</TerminalHighlight> {props.children}
        </TerminalLine>
    )
}
