// website/imyan.ren/src/lib/components/waline/waline.svelte
<script lang="ts">
  import { i18n } from '$lib/i18n'

  interface Props {
    path?: string
    serverURL: string
    [key: string]: any
  }

  let { path, serverURL, ...others }: Props = $props()

  const elementId = `sodesu-${Math.random().toString(36).slice(2, 9)}`

  $effect(() => {
    const currentLang = i18n.locale
    let instance: any = null
    let active = true

    const init = async () => {
      if (typeof window === 'undefined') return

      const Sodesu = await import('sodesu-comment')
      if (!active) return

      instance = Sodesu.init({
        el: `#${elementId}`,
        path: path || window.location.pathname,
        serverURL,
        login: 'disable',
        lang: currentLang,
        dark: 'auto',
      })
    }

    init()

    return () => {
      active = false
      instance?.destroy()
    }
  })
</script>

<div id="sodesu-wrapper" {...others}>
  <div id={elementId}></div>
</div>

// src/components/waline/waline.tsx
import * as Sodesu from 'sodesu-comment'
import { Component, createEffect, createSignal, JSX, onMount } from 'solid-js'

import { locale } from '@/i18n'

type WalineOptions = Parameters<(typeof Sodesu)['init']>[0] &
  JSX.IntrinsicElements['div']

export const Waline: Component<WalineOptions> = (props) => {
  const [sodesu, setSodesu] = createSignal<ReturnType<
    typeof Sodesu.init
  > | null>(null)

  onMount(() => {
    setSodesu(
      Sodesu.init({
        el: '#sodesu',
        path: props.path,
        serverURL: props.serverURL,
        login: 'disable',
        lang: locale(),
        dark: 'auto',
      })
    )
  })

  createEffect(() => sodesu()?.update({ lang: locale() }))

  return (
    <div id="sodesu-wrapper" {...props}>
      <div id="sodesu" />
    </div>
  )
}
