// src/components/waline/waline.tsx
import * as Sodesu from 'sodesu-comment'
import { Component, createEffect, createSignal, JSX, onMount } from 'solid-js'

import { locale } from '@/i18n'

type WalineOptions = Parameters<(typeof Sodesu)['init']>[0] &
  JSX.IntrinsicElements['div']

export const Waline: Component<WalineOptions> = (props) => {
  const [sodesu, setSodesu] = createSignal<ReturnType<
    typeof Sodesu.init
  > | null>(null)

  onMount(() => {
    setSodesu(
      Sodesu.init({
        el: '#sodesu',
        path: props.path,
        serverURL: props.serverURL,
        login: 'disable',
        lang: locale(),
        dark: 'auto',
      })
    )
  })

  createEffect(() => sodesu()?.update({ lang: locale() }))

  return (
    <div id="sodesu-wrapper" {...props}>
      <div id="sodesu" />
    </div>
  )
}

// src/lib/components/waline/waline.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import { getLocale } from '$lib/i18n'

  interface Props {
    path?: string
    serverURL: string
    [key: string]: any
  }

  let { path, serverURL, ...others }: Props = $props()

  let sodesu: any = null

  onMount(async () => {
    if (typeof window !== 'undefined') {
      const Sodesu = await import('sodesu-comment')
      sodesu = Sodesu.init({
        el: '#sodesu',
        path: path || window.location.pathname,
        serverURL,
        login: 'disable',
        lang: getLocale(),
        dark: 'auto',
      })
    }
  })

  $effect(() => {
    const l = getLocale()
    sodesu?.update({ lang: l })
  })
</script>

<div id="sodesu-wrapper" {...others}>
  <div id="sodesu"></div>
</div>
