// website/imyan.ren/src/lib/components/scroll-reveal/scroll-reveal.svelte
<script lang="ts">
  interface Props {
    children?: import('svelte').Snippet
    delay?: number
    threshold?: number
  }

  let { children, delay = 0, threshold = 0.1 }: Props = $props()

  let isVisible = $state(false)

  function reveal(node: HTMLElement) {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            isVisible = true
            observer.unobserve(entry.target)
          }
        })
      },
      { threshold },
    )

    observer.observe(node)

    return {
      destroy() {
        observer.disconnect()
      },
    }
  }
</script>

<div
  use:reveal
  class="scroll-reveal"
  class:is-visible={isVisible}
  style:transition-delay="{delay}ms"
>
  {@render children?.()}
</div>

<style>
  .scroll-reveal {
    opacity: 0;
    transform: translateY(20px);
    transition:
      opacity 0.45s cubic-bezier(0.4, 0, 0.2, 1),
      transform 0.45s cubic-bezier(0.4, 0, 0.2, 1);
  }

  .scroll-reveal.is-visible {
    opacity: 1;
    transform: translateY(0);
  }
</style>

// src/components/scroll-reveal/scroll-reveal.tsx
import {
  type ParentComponent,
  createSignal,
  onMount,
  onCleanup,
} from 'solid-js'
import './scroll-reveal.css'

interface ScrollRevealProps {
  delay?: number
  threshold?: number
}

export const ScrollReveal: ParentComponent<ScrollRevealProps> = (props) => {
  const [isVisible, setIsVisible] = createSignal(false)
  let ref: HTMLDivElement | undefined

  onMount(() => {
    if (!ref) return

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setTimeout(() => {
              setIsVisible(true)
            }, props.delay || 0)
            observer.unobserve(entry.target)
          }
        })
      },
      { threshold: props.threshold || 0.1 },
    )

    observer.observe(ref)

    onCleanup(() => observer.disconnect())
  })

  return (
    <div ref={ref} class="scroll-reveal" classList={{ visible: isVisible() }}>
      {props.children}
    </div>
  )
}
