// src/lib/components/image-with-placeholder/image-with-placeholder.svelte
<script lang="ts">
  import './image-with-placeholder.css'

  interface Props {
    src: string
    alt: string
    class?: string
    imgClass?: string
    loading?: 'lazy' | 'eager'
    onerror?: (e: Event) => void
  }

  let {
    src,
    alt,
    class: className,
    imgClass,
    loading = 'lazy',
    onerror,
  }: Props = $props()

  let isLoading = $state(true)

  $effect(() => {
    // Reset loading when src changes
    src
    isLoading = true
  })
</script>

<div class="img-placeholder-container {className || ''}">
  {#if isLoading}
    <div class="img-placeholder-shim"></div>
  {/if}

  <img
    class="img-with-placeholder {imgClass || ''} {isLoading
      ? 'is-loading'
      : ''}"
    {src}
    {alt}
    {loading}
    decoding="async"
    onload={() => (isLoading = false)}
    onerror={(e) => {
      isLoading = false
      onerror?.(e)
    }}
  />
</div>

// src/components/image-with-placeholder/image-with-placeholder.tsx
import { Component, createSignal, Show } from 'solid-js'
import './image-with-placeholder.css'

interface ImageWithPlaceholderProps {
    src: string
    alt: string
    class?: string
    imgClass?: string
    loading?: 'lazy' | 'eager'
    handleError?: (e: Event) => void
}

export const ImageWithPlaceholder: Component<ImageWithPlaceholderProps> = (props) => {
    const [loading, setLoading] = createSignal(true)

    // Reset loading state when src changes
    // Note: specific to SolidJS reactivity, if props.src creates a new tracking context

    return (
        <div class={`img-placeholder-container ${props.class || ''}`}>
            <Show when={loading()}>
                <div class="img-placeholder-shim" />
            </Show>

            <img
                class={`img-with-placeholder ${props.imgClass || ''} ${loading() ? 'is-loading' : ''}`}
                src={props.src}
                alt={props.alt}
                loading={props.loading || 'lazy'}
                decoding="async"
                onLoad={() => setLoading(false)}
                onError={(e) => {
                    setLoading(false)
                    if (props.handleError) {
                        props.handleError(e)
                    }
                }}
            />
        </div>
    )
}
