// src/routes/about/+page.svelte
<script lang="ts">
  import './about.css'
  import Terminal from '$lib/components/terminal/Terminal.svelte'
  import TerminalHighlight from '$lib/components/terminal/TerminalHighlight.svelte'
  import TerminalLine from '$lib/components/terminal/TerminalLine.svelte'
  import TerminalPrompt from '$lib/components/terminal/TerminalPrompt.svelte'
</script>

<div id="about">
  <Terminal class="about-terminal">
    <TerminalPrompt>cat /etc/profile</TerminalPrompt>
    <TerminalLine># Loading user profile configuration...</TerminalLine>
    <TerminalLine>
      module.load('yanren_profile'){' '}
      <TerminalHighlight>...Pending</TerminalHighlight>
    </TerminalLine>
    <TerminalLine>
      {'>'} User profile is currently under construction.
    </TerminalLine>
    <TerminalLine>{'>'} Please check back later.</TerminalLine>
    <TerminalPrompt>
      <span class="cursor"></span>
    </TerminalPrompt>
  </Terminal>
</div>

// src/view/about/about.tsx
import './about.css'

import { Component } from 'solid-js'

import {
    Terminal,
    TerminalHighlight,
    TerminalLine,
    TerminalPrompt,
} from '@/components/terminal/terminal'
import Layout from '@/layout/layout'

export const About: Component = () => {
    return (
        <Layout>
            <div id="about">
                <Terminal class="about-terminal">
                    <TerminalPrompt>cat /etc/profile</TerminalPrompt>
                    <TerminalLine># Loading user profile configuration...</TerminalLine>
                    <TerminalLine>
                        module.load('yanren_profile'){' '}
                        <TerminalHighlight>...Pending</TerminalHighlight>
                    </TerminalLine>
                    <TerminalLine>
                        {'>'} User profile is currently under construction.
                    </TerminalLine>
                    <TerminalLine>{'>'} Please check back later.</TerminalLine>
                    <TerminalPrompt>
                        <span class="cursor" />
                    </TerminalPrompt>
                </Terminal>
            </div>
        </Layout>
    )
}
