// src/view/friend/_components/friend-avatar/friend-avatar.tsx
import { createAvatar } from '@dicebear/core'
import { pixelArt } from '@dicebear/collection'
import { Component } from 'solid-js'

import { ImageWithPlaceholder } from '@/components/image-with-placeholder/image-with-placeholder'

export const FriendAvatar: Component<FriendAvatarProps> = (props) => {
  return (
    <ImageWithPlaceholder
      src={props.avatar ?? ''}
      alt={props.name}
      class={props.class}
      imgClass="friend-avatar-img"
      handleError={(e) => {
        if (e.target instanceof HTMLImageElement) {
          const avatar = createAvatar(pixelArt, {
            seed: props.name,
            scale: 85,
          })
          e.target.src = avatar.toDataUri()
        }
      }}
    />
  )
}

// src/lib/components/friend/friend-avatar/friend-avatar.svelte
<script lang="ts">
  import { createAvatar } from '@dicebear/core'
  import { pixelArt } from '@dicebear/collection'
  import ImageWithPlaceholder from '$lib/components/image-with-placeholder/image-with-placeholder.svelte'

  interface Props {
    class?: string
    name: string
    avatar?: string
  }

  let { class: className, name, avatar }: Props = $props()

  function handleError(e: Event) {
    if (e.target instanceof HTMLImageElement) {
      const newAvatar = createAvatar(pixelArt, {
        seed: name,
        scale: 85,
      })
      e.target.src = newAvatar.toDataUri()
    }
  }
</script>

<ImageWithPlaceholder
  src={avatar ?? ''}
  alt={name}
  class={className}
  imgClass="friend-avatar-img"
  onerror={handleError}
/>
