// src/components/scroll-reveal/scroll-reveal.tsx
import {
  type ParentComponent,
  createSignal,
  onMount,
  onCleanup,
} from 'solid-js'
import './scroll-reveal.css'

interface ScrollRevealProps {
  delay?: number
  threshold?: number
}

export const ScrollReveal: ParentComponent<ScrollRevealProps> = (props) => {
  const [isVisible, setIsVisible] = createSignal(false)
  let ref: HTMLDivElement | undefined

  onMount(() => {
    if (!ref) return

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setTimeout(() => {
              setIsVisible(true)
            }, props.delay || 0)
            observer.unobserve(entry.target)
          }
        })
      },
      { threshold: props.threshold || 0.1 },
    )

    observer.observe(ref)

    onCleanup(() => observer.disconnect())
  })

  return (
    <div ref={ref} class="scroll-reveal" classList={{ visible: isVisible() }}>
      {props.children}
    </div>
  )
}

// src/lib/components/scroll-reveal/scroll-reveal.svelte
<script lang="ts">
  import './scroll-reveal.css'
  import { onMount } from 'svelte'

  interface Props {
    children?: import('svelte').Snippet
    delay?: number
    threshold?: number
  }

  let { children, delay = 0, threshold = 0.1 }: Props = $props()

  let isVisible = $state(false)
  let ref: HTMLDivElement

  onMount(() => {
    if (!ref) return

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setTimeout(() => {
              isVisible = true
            }, delay)
            observer.unobserve(entry.target)
          }
        })
      },
      { threshold },
    )

    observer.observe(ref)

    return () => observer.disconnect()
  })
</script>

<div bind:this={ref} class="scroll-reveal" class:visible={isVisible}>
  {@render children?.()}
</div>
