// shared/common/src/lib/mouse/mouse-light/mouse-light.svelte
<script lang="ts">
  interface Props {
    as?: string
    class?: string
    children?: import('svelte').Snippet
    [key: string]: any
  }

  let {
    as: tag = 'div',
    class: className,
    children,
    ...others
  }: Props = $props()

  const onMouseMove = (e: MouseEvent) => {
    const element = e.currentTarget as HTMLElement
    const rect = element.getBoundingClientRect()
    const x = e.clientX - rect.left
    const y = e.clientY - rect.top
    element.style.setProperty('--mouse-x', `${x}px`)
    element.style.setProperty('--mouse-y', `${y}px`)
  }
</script>

<svelte:element
  this={tag}
  class="mouse-light {className || ''}"
  onmousemove={onMouseMove}
  {...others}
>
  <div class="light-effect"></div>
  {@render children?.()}
</svelte:element>

<style>
  .mouse-light {
    position: relative;
    overflow: hidden;
  }

  .mouse-light .light-effect {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    opacity: 0;
    background: radial-gradient(
      300px circle at var(--mouse-x, 50%) var(--mouse-y, 50%),
      rgb(from var(--c-text) r g b / 0.03),
      transparent 40%
    );
    transition: opacity 0.3s;
    pointer-events: none;
    z-index: 1;
  }

  .mouse-light:hover .light-effect {
    opacity: 1;
  }

  .mouse-light > *:not(.light-effect) {
    position: relative;
    z-index: 2;
  }
</style>

// src/components/mouse-light/mouse-light.tsx
import { type JSX, type Component, splitProps } from 'solid-js'
import { Dynamic } from 'solid-js/web'
import './mouse-light.css'

type MouseLightProps = {
  as?: string
  children?: JSX.Element
  [key: string]: any
}

export const MouseLight: Component<MouseLightProps> = (props) => {
  const [local, others] = splitProps(props, [
    'as',
    'children',
    'class',
    'classList',
  ])

  const handleMouseMove = (e: MouseEvent) => {
    const element = e.currentTarget as HTMLElement
    const rect = element.getBoundingClientRect()
    const x = e.clientX - rect.left
    const y = e.clientY - rect.top
    element.style.setProperty('--mouse-x', `${x}px`)
    element.style.setProperty('--mouse-y', `${y}px`)
  }

  return (
    <Dynamic
      component={local.as || 'div'}
      class={`mouse-light ${local.class || ''}`}
      classList={local.classList}
      onMouseMove={handleMouseMove}
      {...others}
    >
      <div class="light-effect" />
      {local.children}
    </Dynamic>
  )
}
